### ISSUE TITLE
小小的建议

### ISSUE THREAD

**Issue by Fahaxikiii** [AdminWhaleFall/SkyDailyTask#3]
作者你好，能否实现通过QQ机器人每日定时发送，感觉邮箱有点麻烦。

**Comment by davidelectricfree** [comment]
@AdminWhaleFall 感谢作者的项目，我已经把光遇攻略集成到我的QQ机器人了，方法是直接对你的github readme页面进行自动截图操作，生成图片，QQ机器人那边使用关键词触发即可。
